### PR TITLE
Fix typo in landing.tsx.

### LINKED ISSUE #10817: Typo in MDN Curriculum home page
Just a small typo, but can it be "high-quality" if it's spelled wrong? ;-)

https://github.com/mdn/yari/blob/685cde73e29fb55a764e873f5179dc16e6641fc8/client/src/curriculum/landing.tsx#L86

### PR DESCRIPTION
**Pull request by hobbsd**
Fix a typo: from "hight-quality" to "high-quality".

## Summary

Fixes #10817.

### Problem

A typo on the Curriculum landing page.

### Solution

Remove an extraneous "t".

---

### After

---

### CODE REVIEW

**Review by skyclouds2001 — COMMENTED** [review]
I guess you open the PR at the incorrect position...

**Comment by hobbsd** [comment]
Sorry, could you explain what you mean?

**Comment by skyclouds2001** [comment]
you should open the PR at mdn/yari

**Comment by hobbsd** [comment]
Ah, thanks! I thought linking it to the issue did that. I'll try again.

**Pull request closed without merging**
